### ISSUE TITLE
Avatars are too small

### ISSUE THREAD

**Issue by akulihin** [mylorik/King-of-the-Garbage-Hill#1]
### Problem:
Avatars in the game are too small.

### Solution: 
Move the avatar from the main menu to the character description replacing `WithThumbnailUrl` with `WithImageUrl` method.

**Comment by sirinoks** [comment]
Fixed in 00aa315374ec6d543190b3c40bbd0b83ccfe13d5 , testing required.

**Comment by sirinoks** [comment]
Moved avatar placement in 377aaa8c3d0122492eb273e2b8527e31e9a1f2aa

**Comment by mylorik** [comment]
The second commit fixes the problem, thank you!
