### ISSUE TITLE
Characters are missing avatars

### ISSUE THREAD

**Issue by akulihin** [mylorik/King-of-the-Garbage-Hill#2]
### Problem:
The following characters are missing avatars despite having the file in the game files

### Solution:
Upload avatar images to a reputable hosting and update characters.json to indicate a new url.
We can use Discord's CDN since this will be the fastest hosting for a Discord game

**Comment by sirinoks** [comment]
Fixed in [fc00fa3](https://github.com/mylorik/King-of-the-Garbage-Hill/commit/fa343038c26387c2c62e342cbe01b7668a5bf378).
Testing required.

**Comment by mylorik** [comment]
Looks good, thank you! Discord CDN should last for as long as Discord itself :D
